name: "Tests"

on: [pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
        composer test