name: "Tests"

on: [pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
        docker run --rm -v $PWD:/app -w /app php:8.3-cli

        sh -c " \
          apt-get update && \
          apt-get install -y composer zip unzip git && \ 
          composer install --no-interaction --no-dev --optimize-autoloader && \
          ./vendor/bin/phpunit && composer test
        "